name: Il2CppInspectorRedux Build

on: [push, workflow_dispatch, workflow_call]

jobs:
  build-old-gui:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v5
        with:
          submodules: true
          sparse-checkout: |
            VersionedSerialization
            VersionedSerialization.Generator
            Il2CppInspector.Common
            Il2CppInspector.GUI

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'

      - uses: actions/cache@v4
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-gui-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
              ${{ runner.os }}-nuget-gui-

      - name: Restore NuGet packages
        run: dotnet restore -r win-x64 ./Il2CppInspector.GUI

      - name: Build GUI
        run: dotnet publish -c Release --no-self-contained --no-restore -o ./win-x64 -r win-x64 ./Il2CppInspector.GUI/Il2CppInspector.GUI.csproj

      - name: Upload GUI artifact
        uses: actions/upload-artifact@v4
        with:
          name: Il2CppInspectorRedux.Legacy.GUI
          path: ./win-x64
